#
# Component Makefile
#

COMPONENT_SRCDIRS := src src/littlefs

COMPONENT_ADD_INCLUDEDIRS := include

COMPONENT_PRIV_INCLUDEDIRS := src

COMPONENT_SUBMODULES := src/littlefs

CPPFLAGS += \
	-DLFS_CONFIG=lfs_config.h

ifdef CONFIG_LITTLEFS_FCNTL_GET_PATH
	CPPFLAGS += \
		-DF_GETPATH=$(CONFIG_LITTLEFS_FCNTL_F_GETPATH_VALUE)
endif
